### ISSUE TITLE
Make dead people look dead!!!!

### ISSUE THREAD

**Issue by Daniel-s-Walker** [EpicTanks/BOTW#79]
I've added an image to portraits! Simply change the paint method of the character sheet to draw this image over a portrait to denote a dead character. (is hp <= 0 )!!!! This will take one second! but will require a new variable so the UML will get hecked!
![death](https://cloud.githubusercontent.com/assets/24272889/22079664/ae496c5a-dd8a-11e6-9f45-3b533417c46d.png)

**Comment by EpicTanks** [comment]
dunzo
